advanced-config: false
created-at: 1653562015596042200
created-by: UMUTATALAY\user
modified-at: 1653562133951578700
modified-by: UMUTATALAY\user
production-ready: false
project-container-name: blogql
project-name: blogql
